#!/bin/bash

prompt=$1

name_regex='^[A-ZĄĆĘŁŃÓŚŹŻ][a-ząćęłńóśźż]*$'
postal_code_regex='^[0-9]{2}-[0-9]{3}$'
email_regex='^[a-zA-Z0-9+_]+@([a-zA-Z0-9]+\.|)[a-zA-Z0-9]+\.[a-zA-Z]+$'

if [[ $prompt =~ $name_regex ]]; then
    echo "imię"
elif [[ $prompt =~ $postal_code_regex ]]; then
    echo "kod pocztowy"
elif [[ $prompt =~ $email_regex ]]; then
    echo "email"
else
    echo "nie wiem"
fi



